### ISSUE TITLE
Single page error

### ISSUE THREAD

**Issue by JessedeDoes** [LanguageMachines/PICCL#10]
Piccl (picclservice in clam) fails when provided with a single-page image.

Problem is in the foliacat step:

 if [ -f .tif.folia.xml ]; then
      #only one file, nothing to cat
      cp $foliainput levi010geil01_01_Deel330.folia.xml
  else
      foliainput=$(ls -1v *.tif.folia.xml)
      foliacat -i levi010geil01_01_Deel330 -o levi010geil01_01_Deel330.folia.xml $foliainput
  fi

apparently, foliainput is not defined

[error.log.mijnVierdePoging.txt](https://github.com/LanguageMachines/PICCL/files/1626647/error.log.mijnVierdePoging.txt)

**Comment by proycon** [comment]
Hmm, that was addressed in commit 1ad2dc8509e9b4d9d2454aadc98104960837b5ab (part of issue #3), but it seems that didn't fix it properly...

**Comment by proycon** [comment]
Right, that was silly.. should be fixed now...
