### ISSUE TITLE
Frog workflow in CLAM webapp/service

### ISSUE THREAD

**Issue by martinreynaert** [LanguageMachines/PICCL#12]
Please integrate the available Frog NextFlow workflow into the existing PICCL webapp/service.

**Comment by proycon** [comment]
Implemented and tested on ``BAObi1-ds.ocr.folia.xml`` (Dutch Martinet sample data, Kalliopi selection).

Frog is opt-in and will obviously only work for Dutch, the pipeline will refuse to start if you enable it with another language. As a bonus though, I enabled tokenisation through ucto as a postprocessing step (another opt-in parameter) which should work for most of the other languages as well.
