### ISSUE TITLE
Fix travis tests

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/PICCL#16]
Tests run fine locally but something still fails on travis...

**Comment by proycon** [comment]
Tests should use new LaMachine v2 ``proycon/lamachine:piccl`` docker image when released  (#26) (for data and dependencies), not for nextflow scripts.

**Comment by proycon** [comment]
Tests pass again locally at least

**Comment by proycon** [comment]
I want to try to get PICCL in a cleaner state, considering the amount of issues that popped up recently (thanks @pdekker12!); things are way too buggy currently. Better integration tests are essential so let's start by getting the existing continuous integration tests up and running properly again. Continuous integration on travis-ci is a bit challenging considering the many dependencies to install (requires a whole LaMachine deployment) and the fact that many tests are still too large (on too many documents).

First step is to get the development branches of PICCL and ticcltools compatible (i.e. solve #35), after that, when the few automated tests we have are in order, we can do a new 'stablish' release of ticcltools (along with PICCL) as some things have been fixed in the meantime and hopefully progressed since February. This does go a bit against the discussion with INT we had about not changing too much for a while, but I think the current status-quo isn't very satisfactory either.

**Comment by peterdekker** [comment]
@proycon Continuous integrations tests sound good, also for our deployment of PICCL, especially for the long run.

For the very short term, our interest would be to have the minimum pipeline working and then freeze the code for a moment.
It would be very nice if you could fix https://github.com/LanguageMachines/foliautils/issues/21 (related: #30) and #29 in the coming days, so the pipeline from scan to annotated corpus is working. (Starting at an intermediate step is not possible, but that could be fixed later then.) If you could then freeze the master branch for a few days, we will immediately install a production server. After it has been tested and everything works (in those few days), we do not mind any changes to master.

Let me know if this would work for you!

**Comment by proycon** [comment]
Yes, we will do the fixes and publish new releases of PICCL, Ticcltools and probably also foliautils. LaMachine stable automatically uses these latest releases, so master branch development on PICCL, Ticcltools and most of our other tools (with the notable exception of LaMachine itself) shouldn't have an impact your production environment anyway (assuming you are not using the development version of LaMachine).

I think you mean another issue rather than #21 right? That one is already closed.

**Comment by peterdekker** [comment]
Thanks, that is good to hear! We indeed use the stable version of LaMachine, so that sounds good.

Sorry, I meant foliautils issue 21: https://github.com/LanguageMachines/foliautils/issues/21

**Comment by kosloot** [comment]
Which should be solved now.

**Comment by proycon** [comment]
The tests have been fixed and continuous integration on travis works again. They are limited as they currently only check whether the desired output is produced (and whether that is valid FoLiA), rather than actually testing the quality of the contents.

@martinreynaert I would *strongly* recommend expanding these tests whenever new functionality is added to the workflow. Simply adapt ``test.sh``. Ensure that the tests are as small as possible (this is not the place for big data tests), say one or two two pages at most, so travis can run them. If you add larger tests, you can exclude them from travis (I did for one). You can run the tests in any LaMachine installation that has PICCL installed.

**Comment by proycon** [comment]
@pdekker12 The new PICCL and dependencies are released, can you guys give it a try?

**Comment by peterdekker** [comment]
Thanks! I am testing it right now
