### ISSUE TITLE
Sth. wrong with default DEU-frak lexicon

### ISSUE THREAD

**Issue by martinreynaert** [LanguageMachines/PICCL#18]
When trying to run a test on the Bolzano books, I immediately get an error about the lexicon.

Please see: 

https://webservices-lst.science.ru.nl/piccl/DPO35pdf2txt/output/error.log

**Comment by proycon** [comment]
Not related to the german lexicon as such, but was a bug in the wrapper upon reusing a project. should be fixed now

**Comment by proycon** [comment]
Fixed
