### ISSUE TITLE
Downloading books/docs from a URL

### ISSUE THREAD

**Issue by martinreynaert** [LanguageMachines/PICCL#19]
Since my upload capacity from home is insufficient to upload a book's PDF to PICCL (failed twice on Morse book yesterday, failed again on <25MB Martinet DPO35 PDF just now) I would like CLAM's option to download from a URL activated.

This will allow me to see if users might download a book from KB Delpher directly given that they have first determined the PDF's permanent URL. For DPO35 this is: 

https://resolver.kb.nl/resolve?urn=dpo:35:mpeg21:pdf

**Comment by proycon** [comment]
Implemented and deployed
