### ISSUE TITLE
Deliverable: 'instappunten': making TICCL optional

### ISSUE THREAD

**Issue by martinreynaert** [LanguageMachines/PICCL#21]
According to the CLARIAH PICCL deliverables we need to provide diverse acces points to the system. We now have three major components: Tesseract, TICCL and Frog. Frog being usefull for Dutch only is already optional in the web version. TICCL should run by default after OCR, but it should also be possible for the user to specify that it should not be run. In which case, the user should still be able to run Ucto and/or Frog on the non-TICCLED OCRed or otherwise obtained input text.

**Comment by proycon** [comment]
Implemented and deployed, but not tested yet. 

@martinreynaert, can you test?

**Comment by martinreynaert** [comment]
Tested! This works. Thanks, proycon!
