### ISSUE TITLE
Files with spaces in filename not handled

### ISSUE THREAD

**Issue by bloemj** [LanguageMachines/PICCL#24]
The pdfimages command fails to execute when the input file has spaces in the name, as the file name is not enclosed in quotes in the command.
[error.log](https://github.com/LanguageMachines/PICCL/files/1804061/error.log)

**Comment by proycon** [comment]
Right, the pipeline currently doesn't work well with spaces in input files. This needs to be explicitly addressed because as it stands it's even a security risk for shell injection attacks....

**Comment by proycon** [comment]
(spaces in filenames remain unsupported for the time being)
