### ISSUE TITLE
Test current PICCL ocr & ticcl pipelines; with and without webservice wrapper, and see if expectations are met

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/PICCL#3]

**Comment by martinreynaert** [comment]
Test2

In Test 1 we learned that as a new user we did not have the permissions to initialise Nextflow PICCL from the LaMachine command-line. Proycon set these right. Now we log on again we find that the lexicons and test corpora we installed appear not to be there anymore.

We further find we do no have the necessary permissions again.

mre

**Comment by martinreynaert** [comment]
Documentation to go with previous comment:

(lamachine)mreynaert@scootaloo:~/PICCLtest$ ls -l
total 0
(lamachine)mreynaert@scootaloo:~/PICCLtest$ nextflow run LanguageMachines/PICCL
/bin/bash: /vol/customopt/lamachine/bin/nextflow: Permission denied
(lamachine)mreynaert@scootaloo:~/PICCLtest$ nextflow run LanguageMachines/PICCL/download-data.nf
/bin/bash: /vol/customopt/lamachine/bin/nextflow: Permission denied
(lamachine)mreynaert@scootaloo:~/PICCLtest$ nextflow run LanguageMachines/PICCL/download-examples.nf
/bin/bash: /vol/customopt/lamachine/bin/nextflow: Permission denied
(lamachine)mreynaert@scootaloo:~/PICCLtest$

**Comment by proycon** [comment]
``/vol/customopt/lamachine/bin/nextflow`` permission fixed on ponyland

**Comment by martinreynaert** [comment]
After downloaden the lexicons and the data I have two dirs. The first does hold the lexicons and alphabets etc. The second does not have the test data.

```
(lamachine)mreynaert@scootaloo:~/PICCLtest$ nextflow run LanguageMachines/PICCL/download-data.nf
N E X T F L O W  ~  version 0.25.7
Launching `LanguageMachines/PICCL` [soggy_mestorf] - revision: 62298d34f5 [master]
--------------------------
Download data for PICCL
--------------------------
[warm up] executor > local
[2f/8c7836] Submitted process > download
(lamachine)mreynaert@scootaloo:~/PICCLtest$

Something is not quite right. The data/ data seem to be replicated in each work/ dir. I do not find my test corpora.

(lamachine)mreynaert@scootaloo:~/PICCLtest$ ls -l
total 8
drwxrwsr-x 3 mreynaert mreynaert 4096 Oct 16 16:19 data
drwxrwsr-x 4 mreynaert mreynaert 4096 Oct 16 16:18 work
(lamachine)mreynaert@scootaloo:~/PICCLtest$ ls -l work
total 8
drwxrwsr-x 3 mreynaert mreynaert 4096 Oct 16 16:18 2f
drwxrwsr-x 3 mreynaert mreynaert 4096 Oct 16 16:17 6b
(lamachine)mreynaert@scootaloo:~/PICCLtest$ ls -l work/2f
total 4
drwxrwsr-x 3 mreynaert mreynaert 4096 Oct 16 16:19 8c7836ad49cd0fd0d26e3da3494588
(lamachine)mreynaert@scootaloo:~/PICCLtest$ ls -l data/
total 72
-rw-rw-r--  1 mreynaert mreynaert 67947 Oct 16 16:19 dbnl_ozt_ids.txt
drwxrwsr-x 21 mreynaert mreynaert  4096 Oct 16 16:19 int
(lamachine)mreynaert@scootaloo:~/PICCLtest$ 
(lamachine)mreynaert@scootaloo:~/PICCLtest$ ls -l data/int
total 76
drwxrwsr-x 2 mreynaert mreynaert 4096 Oct 16 16:19 deu
drwxrwsr-x 2 mreynaert mreynaert 4096 Oct 16 16:19 deu-frak
drwxrwsr-x 2 mreynaert mreynaert 4096 Oct 16 16:19 ell
-rw-r--r-- 1 mreynaert mreynaert    1 Oct 16 16:19 empty.lst
drwxrwsr-x 2 mreynaert mreynaert 4096 Oct 16 16:19 eng
drwxrwsr-x 2 mreynaert mreynaert 4096 Oct 16 16:19 fin
drwxrwsr-x 2 mreynaert mreynaert 4096 Oct 16 16:19 fra
drwxrwsr-x 2 mreynaert mreynaert 4096 Oct 16 16:19 fry
drwxrwsr-x 2 mreynaert mreynaert 4096 Oct 16 16:19 grc
drwxrwsr-x 2 mreynaert mreynaert 4096 Oct 16 16:19 isl
drwxrwsr-x 2 mreynaert mreynaert 4096 Oct 16 16:19 ita
drwxrwsr-x 2 mreynaert mreynaert 4096 Oct 16 16:19 lat
drwxrwsr-x 2 mreynaert mreynaert 4096 Oct 16 16:19 nld
drwxrwsr-x 2 mreynaert mreynaert 4096 Oct 16 16:19 pol
drwxrwsr-x 2 mreynaert mreynaert 4096 Oct 16 16:19 por
drwxrwsr-x 2 mreynaert mreynaert 4096 Oct 16 16:19 ron
drwxrwsr-x 2 mreynaert mreynaert 4096 Oct 16 16:19 rus
drwxrwsr-x 2 mreynaert mreynaert 4096 Oct 16 16:19 spa
drwxrwsr-x 2 mreynaert mreynaert 4096 Oct 16 16:19 swe
(lamachine)mreynaert@scootaloo:~/PICCLtest$ ls -l data/int/deu-frak/
total 6200
-rw-r--r-- 1 mreynaert mreynaert 3825910 Oct 16 16:19 deu-frak.aspell.dict
-rw-r--r-- 1 mreynaert mreynaert 2512524 Oct 16 16:19 deu-frak.aspell.dict.c0.d2.confusion
-rw-r--r-- 1 mreynaert mreynaert     740 Oct 16 16:19 deu-frak.aspell.dict.lc.chars
(lamachine)mreynaert@scootaloo:~/PICCLtest$ ls -l data/int/nl
ls: cannot access data/int/nl: No such file or directory
(lamachine)mreynaert@scootaloo:~/PICCLtest$ ls -l data/int/nld
total 25388
-rw-r--r-- 1 mreynaert mreynaert  5897207 Oct 16 16:19 ARG4.SGDLEX.UTF8.TICCL.v.4.lst
-rw-r--r-- 1 mreynaert mreynaert  2605708 Oct 16 16:19 nld.aspell.dict
-rw-r--r-- 1 mreynaert mreynaert  5064047 Oct 16 16:19 nld.aspell.dict.c20.d2.confusion
-rw-r--r-- 1 mreynaert mreynaert      839 Oct 16 16:19 nld.aspell.dict.lc.chars
-rw-r--r-- 1 mreynaert mreynaert 12410216 Oct 16 16:19 nuTICCL.OldandINLlexandINLNamesAspell.v2.COL1.tsv
(lamachine)mreynaert@scootaloo:~/PICCLtest$ ls -l work/2f/8c7836ad49cd0fd0d26e3da3494588/
total 72
-rw-rw-r--  1 mreynaert mreynaert 67947 May  9 18:07 dbnl_ozt_ids.txt
drwxr-sr-x 21 mreynaert mreynaert  4096 Jan 13  2016 int
(lamachine)mreynaert@scootaloo:~/PICCLtest$ ls -l work/2f/8c7836ad49cd0fd0d26e3da3494588/int/
total 76
drwxr-sr-x 2 mreynaert mreynaert 4096 Sep 20  2014 deu
drwxr-sr-x 2 mreynaert mreynaert 4096 Sep 20  2014 deu-frak
drwxr-sr-x 2 mreynaert mreynaert 4096 Sep 21  2014 ell
-rw-r--r-- 1 mreynaert mreynaert    1 Nov 15  2013 empty.lst
drwxr-sr-x 2 mreynaert mreynaert 4096 Sep 21  2014 eng
drwxr-sr-x 2 mreynaert mreynaert 4096 Sep 22  2014 fin
drwxr-sr-x 2 mreynaert mreynaert 4096 Sep 22  2014 fra
drwxr-sr-x 2 mreynaert mreynaert 4096 Apr 22  2016 fry
drwxr-sr-x 2 mreynaert mreynaert 4096 Sep 22  2014 grc
drwxr-sr-x 2 mreynaert mreynaert 4096 Sep 22  2014 isl
drwxr-sr-x 2 mreynaert mreynaert 4096 Sep 22  2014 ita
drwxr-sr-x 2 mreynaert mreynaert 4096 Sep 22  2014 lat
drwxr-sr-x 2 mreynaert mreynaert 4096 Jan 30  2015 nld
drwxr-sr-x 2 mreynaert mreynaert 4096 Sep 22  2014 pol
drwxr-sr-x 2 mreynaert mreynaert 4096 Sep 22  2014 por
drwxr-sr-x 2 mreynaert mreynaert 4096 Sep 22  2014 ron
drwxr-sr-x 2 mreynaert mreynaert 4096 Sep 22  2014 rus
drwxr-sr-x 2 mreynaert mreynaert 4096 Sep 21  2014 spa
drwxr-sr-x 2 mreynaert mreynaert 4096 Sep 21  2014 swe
(lamachine)mreynaert@scootaloo:~/PICCLtest$ 
```

**Comment by kosloot** [comment]
test

**Comment by martinreynaert** [comment]
reply test

**Comment by martinreynaert** [comment]
again reply test

**Comment by proycon** [comment]
I see no problem, Looks like the data is downloaded fine. Did you run ``download-examples.nf`` as in the README to get the example corpora? (there are two download scripts).

The replication in ``work/`` is okay, it's just a temporary work dir. You can remove it when when a script is done if you don't want to preserve intermediate results.

**Comment by martinreynaert** [comment]
While running:
nohup nextflow run LanguageMachines/PICCL/ocr.nf --inputdir ~/PICCLtest/DIABOR/ --language nld >NFDIABORtest1.stdout 2>NFDIABORtest1.stderr &

we see by way of ps ax:
(lamachine)mreynaert@scootaloo:/vol/tensusers/mreynaert$ ps ax |grep 'foliacat'
 42577 pts/24   R      1:08 /vol/customopt/lamachine/bin/python /vol/customopt/lamachine/bin/foliacat -i levi010geil01_01 -o levi010geil01_01.folia.xml 100.tif.folia.xml 101.tif.folia.xml 102.tif.folia.xml 103.tif.folia.xml 104.tif.folia.xml

This is the wrong sort for book pages. It should be a natural sort.

The best test for this will be to use the deu-frak test set with a number of Bolzano chapters.

**Comment by proycon** [comment]
I'm not sure what you mean here. The order here is ``100.tif.folia.xml 101.tif.folia.xml 102.tif.folia.xml 103.tif.folia.xml 104.tif.folia.xml`` which seems fine to me? What am I missing?

**Comment by martinreynaert** [comment]
What you miss should become clearer when I here paste a small part of the further sequence of these files, book pages ranked to be collated in a single book file by FoLiAcat. Bear in mind that the numbering of scanned pages of a book usually starts at '1'.

Excerpt: "199.tif.folia.xml 19.tif.folia.xml 1.tif.folia.xml 200.tif.folia.xml 201.tif.folia.xml".

What is required here is what this Perl module achieves: http://search.cpan.org/~bingos/Sort-Naturally-1.03/lib/Sort/Naturally.pm . It achieves to properly sort the numbered pages retrieved from several approriately numbered PDFs representing book chapters, e.g. ThisBook.Ch01.pdf, ThisBook.Ch02.pdf, ThisBook.Ch03.pdf, etc. I.e. you need to be able to deal with a possible prefix, book chapter number, a possible infix *and* the actual chapter page numbers.

**Comment by proycon** [comment]
Ok, so that should be ``1.tif.folia.xml  19.tif.folia.xml 199.tif.folia.xml  200.tif.folia.xml 201.tif.folia.xml`` right? That indeed seems a sorting bug we can easily fix then.

**Comment by proycon** [comment]
Sort fix implemented and deployed on ponyland

**Comment by proycon** [comment]
There's still a discrepancy between this and the perl module you mentioned (example from their website). But hopefully okay in our context?

**perl module**: ``9x 14 foo fooa foolio Foolio foo12 foo12a Foo12a foo12z foo13a``

**ls -1v**:  ``9x 14 Foo12a Foolio foo foo12 foo12a foo12z foo13a fooa foolio``

**Comment by martinreynaert** [comment]
After the sort fix results on the Dutch diamondencyclopedia are good: the book;s pages are now collated into a single book in the proper order.

However, testing with separate chapters input as separate PDFs led to an error. Somehow the system lost the prefix to the single file it seemed to have seen.
Command-line:  nohup ocr.nf -with-trace --inputdir ~/PICCLtest/corpora/PDF/DEU-FRAK/BolzanoWLchapters --language nld >NF.WLchapters.test.stdout 2>NF.WLchapters.test.stderr &

Testing again with a single PDF as input worked as it should: command line:
nohup ocr.nf -with-trace --inputdir ~/PICCLtest/corpora/PDF/DEU-FRAK/BolzanoWLdemo --language nld >NF.WLdemo.test.stdout 2>NF.WLdemo.test.stderr &

**Comment by proycon** [comment]
Currently separate input PDFs will never be merged together, the current pipeline is one input PDF -> one output PDF. We could enhance the pipeline by merging PDFs together if the user explicitly indicates (better make a new issue for this then). 

Still, multiple input PDFs should work, I don't know what error you get? You didn't mention it...

**Comment by martinreynaert** [comment]
I got this error:

[77/70ec2d] Submitted process > foliacat (2)
ERROR ~ Error executing process > 'foliacat (3)'

Caused by:
  Process `foliacat (3)` terminated with an error exit status (2)

The cause is documented here:

(lamachine)mreynaert@scootaloo:/vol/tensusers/mreynaert/work$ ls -la 77/70ec2d31fa057c146435ad14191d6d/
total 40
drwxrwxr-x  2 mreynaert mreynaert 4096 Oct 25 15:46 .
drwxrwxr-x 32 mreynaert mreynaert 4096 Oct 25 15:46 ..
-rw-rw-r--  1 mreynaert mreynaert    0 Oct 25 15:46 .command.begin
-rw-rw-r--  1 mreynaert mreynaert  212 Oct 25 15:46 .command.err
-rw-rw-r--  1 mreynaert mreynaert 1317 Oct 25 15:46 .command.log
-rw-rw-r--  1 mreynaert mreynaert 1105 Oct 25 15:46 .command.out
-rw-rw-r--  1 mreynaert mreynaert 1969 Oct 25 15:46 .command.run
-rw-rw-r--  1 mreynaert mreynaert 2649 Oct 25 15:46 .command.run.1
-rw-rw-r--  1 mreynaert mreynaert  214 Oct 25 15:46 .command.sh
-rw-rw-r--  1 mreynaert mreynaert    3 Oct 25 15:46 .command.trace
-rw-rw-r--  1 mreynaert mreynaert    1 Oct 25 15:46 .exitcode
lrwxrwxrwx  1 mreynaert mreynaert   91 Oct 25 15:46 .tif.folia.xml -> /vol/tensusers/mreynaert/work/81/8416eb3026f59d32a846918d179494/WL1_3-002-000.tif.folia.xml
(lamachine)mreynaert@scootaloo:/vol/tensusers/mreynaert/work$ cat 77/70ec2d31fa057c146435ad14191d6d/.command.err
ls: cannot access *.tif.folia.xml: No such file or directory

You can see the file lrwxrwxrwx  1 mreynaert mreynaert   91 Oct 25 15:46 .tif.folia.xml ->  has lost its prefix. 

There should have been far more files, I input three PDFs!

**Comment by proycon** [comment]
Right, the fact that there is one instead of three is expected as they're all done in their own workdir and we don't merge multiple documents. 

But there is indeed a bug here, the prefix apparently gets lost if there is only one input document (not entirely sure why). The underlying issue is that is makes no sense to call foliacat for one document anyway, that task should be skipped in such cases.

**Comment by martinreynaert** [comment]
That means we cannot now reassemble a book that had its chapters in separate PDFs. This is what @PhilosTEI did.

On the other hand, this is what we want if people input separate papers, e.g. I.e. each paper to be handled as a single entity.

For TICCL too this poses a problem: preferably it should work on the frequency file derived from the whole book. Or even from the batch of papers, if these e.g. all from the same genre or about the same topic.

At least for TICCL, we want to be able to aggregate over the various working directories.

**Comment by proycon** [comment]
(Indeed, I just split that one into a new issue: #7)

**Comment by proycon** [comment]
TICCL does work in aggregated fashion already, it uses all input documents in the input directory.

**Comment by proycon** [comment]
I fixed the foliacat bug last week btw but it still requires testing (use development LaMachine on ponyland rather than the normal one), we should best add new test units.

**Comment by proycon** [comment]
I'm closing this one as the issues in here are solve and/or we have more specific and overlapping issues open now.
