### ISSUE TITLE
Running ticcl.nf for folia files with different extension fails

### ISSUE THREAD

**Issue by peterdekker** [LanguageMachines/PICCL#32]
I try to run ticcl.nf for a directory of folia files (vangogh/) which have the extension .xml, instead of .folia.xml. The files have been generated earlier, not with ocr.nf.
When I run:
```
$ ticcl.nf --inputdir vangogh/ --lexicon /vol1/lamachine/piccldata/data/int/nld/nld.aspell.dict --alphabet /vol1/lamachine/piccldata/data/int/nld/nld.aspell.dict.lc.chars --charconfus /vol1/lamachine/piccldata/data/int/nld/nld.aspell.dict.c20.d2.confusion --extension xml
```
It does not process any files.

On line 132 of `ticcl.nf`, FoLiA-stats is invoked with a hardcoded filter `.folia.xml`: https://github.com/LanguageMachines/PICCL/blob/master/ticcl.nf#L132
I tried to change this hardcoded filter to the extension parameter, then the files are found. This may be problematic in other cases: when text of pdf files are processed with a non-standard extension parameter, the script generates .folia.xml files, then FoLiA-stats should not be invoked with the extension parameter.

EDITED: Removed second unrelated problem.

**Comment by pdekker12** [comment]
The second problem (of which I pasted the output) is probably not related to the file extension. It also occurs when I rename all files to *.folia.xml. Maybe there is something wrong with my file format?

**Comment by proycon** [comment]
Well spotted yes, this was overlooked. Fixed in the above commit.

> This may be problematic in other cases: when text of pdf files are processed with a non-standard extension parameter, the script generates .folia.xml files, then FoLiA-stats should not be invoked with the extension parameter.

Hmm, I see what you mean yes, but the parameter only applies to FoLiA, custom extensions are not implemented for other types currently, so this situation shouldn't occur i hope.

**Comment by peterdekker** [comment]
I found an issue related to this: the `foliacorrect` function expects ticcl.folia.xml output from `FoLiA-correct`. In reality, `FoLiA-correct` seems to output .ticcl.+input_extension, which produces .ticcl.xml for .xml files. This results in an error.

**Comment by proycon** [comment]
I added some fixes to remedy this, although this still has not been very much tested. Also, the extension has to end in ``*.xml`` so it's not super flexible yet.

**Comment by peterdekker** [comment]
With the limited set of files I tested with (only *.xml), I can report that this works.
