### ISSUE TITLE
Split list of enrichment steps in webinterface

### ISSUE THREAD

**Issue by peterdekker** [LanguageMachines/PICCL#33]
In the PICCL webinterface, multiple linguistic enrichment steps are offered. In general, most users would want to do the basic processing steps (tokenization, POS tagging and lemmatization). The other steps take more processing time, extra server load, while they give only benefit to users who know what those steps (like dependency parsing) entail.

Would it be possible to split the list of linguistic processing steps in the webinterface, to encourage users to use only the basic processing steps? Possibly the list could be split in "Basic enrichment tasks (recommended)" and "Other enrichment tasks (for advanced users)", or something along those lines.

**Comment by proycon** [comment]
Yes, that'd be a very easy change in the clam service configuration. Leaving it up to @martinreynaert to decide whether he agrees he wants this and to implement the change.

**Comment by peterdekker** [comment]
For future reference, I made an image to propose how a split interface could look. I thought it would also be a good idea to automatically check the basic steps.

![sketch-split-enrichment](https://user-images.githubusercontent.com/5880462/42028743-70f3a6ae-7acd-11e8-8f49-4973532c3dc3.png)

**Comment by proycon** [comment]
Implemented (but not tested or released yet)

**Comment by proycon** [comment]
(released)
