### ISSUE TITLE
Current PICCL not compatible with development versions in TICCL-tools

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/PICCL#35]
TICCL-tools is under heavy development lately and I notice some things are no longer backwards compatible. This is fine (although it implies that PICCL won't work in the LaMachine development version anymore, but that's acceptable as it's development after all). This issue is mainly just a notice for @martinreynaert to be very aware that when new versions of TICCL-tools are eventually released, you have to release a renewed PICCL as well that implements all the necessary changes! 

Example of something that has changed (the ``--corpus`` option on ``TICCL-unk`` seems gone):

```
  TICCL-unk --corpus "eng.aspell.dict" --artifrq 10000000 "corpus.wordfreqlist.tsv"

Command exit status:
  1

Command output:
  (empty)

Command error:
  option-error: invalid option 'corpus'
```

**Comment by kosloot** [comment]
Yes, this option was renamed to --background, as suggested by @martinreynaert

**Comment by proycon** [comment]
Solved

**Comment by proycon** [comment]
This is solved now
