### ISSUE TITLE
TICCL-chain --alph option

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/PICCL#46]
The development version of TICCL-chain now has a mandatory alpha parameter which the latest stable release does not permit. Make sure to update PICCL accordingly when releasing ticcltools.

```
Command error:
  missing --alph option
  mv: cannot stat 'corpus.wordfreqlist.tsv.clean.ldcalc.ranked.chained': No such file or directory
```

**Comment by alankessler** [comment]
Is there a workaround for this?

**Comment by proycon** [comment]
Until @martinreynaert resolves this with new releases of PICCL and ticcltools, the workaround is to use the latest release of ticcltools (which is already over a year old unfortunately), rather than the development (git master) version. This is also what we supply in LaMachine (stable) by default.

**Comment by proycon** [comment]
(this issue is actually an instance of #35)

**Comment by proycon** [comment]
(this has been solved now)
