### ISSUE TITLE
tesseract OCRed output text files throwing error

### ISSUE THREAD

**Issue by Vikas2426** [LanguageMachines/PICCL#47]
![screenshot 250](https://user-images.githubusercontent.com/36814488/54027176-8d368000-41c6-11e9-8457-808c64723cc9.png)

**Comment by proycon** [comment]
Sorry, I missed this issue. I'm not sure if it's still relevant? The problem seems not to be inherently with PICCL but rather a docker issue. How what is invoked?

**Comment by proycon** [comment]
(Expired)
