### ISSUE TITLE
TICCL fails when starting with Folia as input [make TICCL work with non-OCR text classes]

### ISSUE THREAD

**Issue by peterdekker** [LanguageMachines/PICCL#48]
When using the PICCL pipeline (LaMachine, via web interface), TICCL (corpusfrequency) fails when processing a folia file (stellingwerff collection).

We use the following input:
[stellingewerf-aangepast.txt](https://github.com/LanguageMachines/PICCL/files/3148199/stellingewerf-aangepast.txt)

We get this error output, corpusfrequency fails:
[error.log](https://github.com/LanguageMachines/PICCL/files/3148202/error.log)

Could you test and see what causes this problem?

**Comment by martinreynaert** [comment]
Currently TICCL tool FoLiA-stats expects the OCRed text to have class = OCR in the PICCL work flow. Your FoLiA-file does not have that. We shall have to change that in the work flow.

In the meantime, you might run FoLiA-stats by itself, using class = current (which is the default).

I hope this works for you.

**Comment by proycon** [comment]
We indeed need to make the workflow more flexible to allow dealing with FoLiA input which has no specially crafted OCR text class (which is what 95% of the user-supplied input will be probably). Ideally an autodetection stage would be best as users are probably unaware of these details.

**Comment by kosloot** [comment]
Well. As is in practice structure elements can have `<t>` nodes in **multiple** text-classes, it might be quite difficult to guess which one to use.
When using the OCR workflow a text class of OCR is the default, so the I suggest using OCR then.
In the non-OCR workflow, text class 'current' is still the best candidate imho. 
But a user settable option is surely needed.

**Comment by proycon** [comment]
For the time being I implemented a simpler solution with better guesses for defaults. Advanced users can override the input textclass in the input parameters.
