### ISSUE TITLE
Continuous integration failure since FoLiA v1.5?

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/PICCL#5]
See https://travis-ci.org/LanguageMachines/PICCL/builds/291501050

**Comment by kosloot** [comment]
Without the generated intermediate files, investigating is difficult.
Wild guess: Does PICL use the most recent foliautils from GIT, or the release version?
The latter will fail.

**Comment by proycon** [comment]
That seems to be it indeed. The current PICCL test uses the stable LaMachine. Locally with development releases I don't run into this problem.... By the way, does foliautils happen to be release ready?

**Comment by proycon** [comment]
Tests pass locally again (dev lamachine)

**Comment by proycon** [comment]
Test pass locally with stable LaMachine too, but travis still complains..

**Comment by proycon** [comment]
Ah.. caused by docker image not having caught up with the last update yet.. new docker bulld in progress
