### ISSUE TITLE
PICCL no longer installable due to HTTP 404 on downloading examples/data 

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/PICCL#55]
PICCL installation in LaMachine fails when downloading:
   https://ticclops.uvt.nl/TICCL.languagefiles.ALLavailable.20160421.tar.gz

This produces a 404 and results in PICCL not being installable anymore for anyone.

@martinreynaert: Did something happen to that server? Will it be up again? Otherwise we need to move the files somewhere else.

**Comment by proycon** [comment]
works again!

**Comment by bloemj** [comment]
Thanks!
