### ISSUE TITLE
 more elegant error handling needed

### ISSUE THREAD

**Issue by Irishx** [LanguageMachines/PICCL#59]
if ticcl is applied to a list of one word, and it cannot find correction candidates, it gives this error:

ERROR: Expected output corpus.wordfreqlist.tsv.clean.indexNT does not exist or is empty

--> but this is not so much an error, as just a feature of the spelling checker who was intended for full texts.
We should give a more informatie error here.

**Comment by proycon** [comment]
I already pushed a commit that addresses this: https://github.com/LanguageMachines/PICCL/commit/8de0395c4823b53cba6efb1ea1c544eae5a9d67f
